name: smartis_desktop
description: Persian/English Smartis Windows desktop voice assistant.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  audioplayers: ^6.8.1
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
