@echo off
setlocal EnableExtensions
cd /d "%~dp0frontend"
if errorlevel 1 goto :error

echo ============================================================
echo SMARTIS WINDOWS FRONTEND
echo ============================================================

echo [1/4] Checking Flutter Windows project...
if not exist "windows\CMakeLists.txt" (
    echo Windows project files are missing. Regenerating...
    call flutter create --platforms=windows .
    if errorlevel 1 goto :error
)

if not exist "windows\flutter\CMakeLists.txt" (
    echo Flutter managed Windows build files are missing. Regenerating...
    call flutter create --platforms=windows .
    if errorlevel 1 goto :error
)

if not exist "windows\flutter\CMakeLists.txt" (
    echo ERROR: Flutter did not recreate windows\flutter\CMakeLists.txt.
    goto :error
)

echo [2/4] Getting Flutter packages...
call flutter pub get
if errorlevel 1 goto :error

echo [3/4] Verifying generated Flutter Windows files...
if not exist "windows\flutter\generated_plugins.cmake" (
    echo ERROR: generated_plugins.cmake was not generated by flutter pub get.
    echo Try REPAIR_WINDOWS.bat for a clean regeneration.
    goto :error
)

echo [4/4] Starting Smartis...
call flutter run -d windows
set "EXIT_CODE=%ERRORLEVEL%"
if not "%EXIT_CODE%"=="0" goto :error

endlocal
exit /b 0

:error
echo.
echo Smartis frontend failed to start.
echo Run REPAIR_WINDOWS.bat if Flutter or CMake reports a project error.
pause
endlocal & exit /b 1
